// * ---- USERS ---- *

export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'AUTH_FAIL';

export const SIGNOUT_START = 'SIGNOUT_START';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_FAIL = 'SIGNOUT_FAIL';

export const ADD_USER_START = 'ADD_USER_START';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const ADD_USER_FAIL = 'ADD_USER_FAIL';

export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const OPEN_EDIT_USER_MODAL = 'OPEN_EDIT_USER_MODAL';
export const CLOSE_EDIT_USER_MODAL = 'CLOSE_EDIT_USER_MODAL';

export const EDIT_USER_START = 'EDIT_USER_START';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';

export const GET_TEACHER_START = 'GET_TEACHER_START';
export const GET_TEACHER_SUCCESS = 'GET_TEACHER_SUCCESS';
export const GET_TEACHER_FAIL = 'GET_TEACHER_FAIL';

export const GET_STUDENT_START = 'GET_STUDENT_START';
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS';
export const GET_STUDENT_FAIL = 'GET_STUDENT_FAIL';


// * ---- CLASSES ---- *

export const ADD_CLASS_START = 'ADD_CLASS_START';
export const ADD_CLASS_SUCCESS = 'ADD_CLASS_SUCCESS';
export const UPDATE_CLASS_SUCCESS = 'UPDATE_CLASS_SUCCESS';
export const ADD_CLASS_FAIL = 'ADD_CLASS_FAIL';

export const DELETE_CLASS_START = 'DELETE_CLASS_START';
export const DELETE_CLASS_SUCCESS = 'DELETE_CLASS_SUCCESS';
export const DELETE_CLASS_FAIL = 'DELETE_CLASS_FAIL';

export const GET_CLASS_START = 'GET_CLASS_START';
export const GET_CLASS_SUCCESS = 'GET_CLASS_SUCCESS';
export const GET_CLASS_FAIL = 'GET_CLASS_FAIL';


// * ---- FACULTY ---- *

export const ADD_FACULTY_START = 'ADD_FACULTY_START';
export const ADD_FACULTY_SUCCESS = 'ADD_FACULTY_SUCCESS';
export const UPDATE_FACULTY_SUCCESS = 'UPDATE_FACULTY_SUCCESS';
export const ADD_FACULTY_FAIL = 'ADD_FACULTY_FAIL';

export const DELETE_FACULTY_START = 'DELETE_FACULTY_START';
export const DELETE_FACULTY_SUCCESS = 'DELETE_FACULTY_SUCCESS';
export const DELETE_FACULTY_FAIL = 'DELETE_FACULTY_FAIL';

export const GET_FACULTY_START = 'GET_FACULTY_START';
export const GET_FACULTY_SUCCESS = 'GET_FACULTY_SUCCESS';
export const GET_FACULTY_FAIL = 'GET_FACULTY_FAIL';


// * ---- GROUP ---- *

export const ADD_GROUP_START = 'ADD_GROUP_START';
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS';
export const ADD_GROUP_FAIL = 'ADD_GROUP_FAIL';

export const REMOVE_GROUP_CLASS = 'REMOVE_GROUP_CLASS';
export const ADD_GROUP_CLASS = 'ADD_GROUP_CLASS';

export const DELETE_GROUP_START = 'DELETE_GROUP_START';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAIL = 'DELETE_GROUP_FAIL';

export const GET_GROUP_START = 'GET_GROUP_START';
export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS';
export const GET_GROUP_FAIL = 'GET_GROUP_FAIL';



// * ---- ATTENDANCE ---- *

export const ADD_ATT_START = 'ADD_ATT_START';
export const ADD_ATT_SUCCESS = 'ADD_ATT_SUCCESS';
export const ADD_ATT_FAIL = 'ADD_ATT_FAIL';

export const GET_ATT_BY_STUDENT_START = 'GET_ATT_BY_STUDENT_START';
export const GET_ATT_BY_STUDENT_SUCCESS = 'GET_ATT_BY_STUDENT_SUCCESS';
export const GET_ATT_BY_STUDENT_FAIL = 'GET_ATT_BY_STUDENT_FAIL';

export const GET_ATT_ADMIN_START = 'GET_ATT_ADMIN_START';
export const GET_ATT_ADMIN_SUCCESS = 'GET_ATT_ADMIN_SUCCESS';
export const GET_ATT_ADMIN_FAIL = 'GET_ATT_ADMIN_FAIL';

export const UPLOAD_ATT_DOC_START = 'UPLOAD_ATT_DOC_START';
export const UPLOAD_ATT_DOC_SUCCESS = 'UPLOAD_ATT_DOC_SUCCESS';
export const UPLOAD_ATT_DOC_FAIL = 'UPLOAD_ATT_DOC_FAIL';

export const ATT_ACTION_START = 'ATT_ACTION_START';
export const ATT_ACTION_SUCCESS = 'ATT_ACTION_SUCCESS';
export const ATT_ACTION_FAIL = 'ATT_ACTION_FAIL';


// * ---- HELPERS ---- *

export const OPEN_DELETE_MODAL = 'OPEN_DELETE_MODAL';
export const CLOSE_DELETE_MODAL = 'CLOSE_DELETE_MODAL';